services:
  postgres:
    image: postgres:16
    container_name: mini_wms_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_wms
    ports:
      - "5433:5432"
    restart: unless-stopped
